- ios/RNCCameraroll.podspec
when pod install in iOS, error occur and hint no homepage in PodSpec
> [BUG]fix no homepage in Podfile

- package.json
- yarn.lock
PR matching the netinfo upgrade https://github.com/react-native-community/react-native-netinfo/pull/42
> fix(app) update dependencies

- android/gradle.properties
This fixes https://github.com/react-native-community/react-native-cameraroll/issues/9
> Rename ReactNativeNetInfo -> ReactNativeCameraRoll in Gradle.properties

- README.md
- example/js/CameraRollExample.js
- example/js/CameraRollView.js
- js/CameraRoll.js
- js/__tests__/__snapshots__/CameraRollTest.js.snap
Fixes #18 (Fails to build/install/test on XCode 10.2)
Fixes #23 (Camera Roll not returning any photos on iOS)
> Default groupTypes to "All"

- ios/RNCAssetsLibraryRequestHandler.m
Fixes #42, CFRelease(NULL) with VIdeo
> [FIX][IOS] Add check to prevent CFRelease(NULL) crash for mimeType

- ios/RNCAssetsLibraryRequestHandler.m
This PR mirrors the PHAsset 'hack' from the below commit:
https://github.com/facebook/react-native/commit/458e70c79d3e12b5ad017d17ccea2fd62c1c3781#diff-3a2b7a4c4ebe5ac224b5a32896c032fb
@JoshuaGross Could you have a look as the reviewer on the original PR/commit?
> fix(lib): mirror fix PHAsset video upload

- ios/RNCAssetsLibraryRequestHandler.m
> fix(lib): move to local variable instead of relying on the string constant

- typings/CameraRoll.d.ts
In the current version (1.1.1) running the TypeScript compiler gives an error 1046 for `CameraRoll.d.ts`:
This PR updates the type file to correctly follow the TypeScript definition file rules. The project now successfully compiles with no TypeScript errors.
All that's needed for testing is to ensure running the TypeScript compiler doesn't result in any errors.
> Fix TypeScript error TS1046

- android/src/main/java/com/reactnativecommunity/cameraroll/CameraRollModule.java
In #47 and #118, users are experiencing problems with pagination on Android. Upon further investigation, I noticed that we're using Date Taken as the pagination value, each time selecting images older than the last image we cared about.
The problem is that there's no guarantee that Date Taken will be unique. In normal usage of a phone camera, it would be, but given that users can import photos from other sources, we were seeing data sets like the following:
```
2020-01-20 15:37:03.216 27527-27703/com.camerarolllazyload I/CameraRoll: Image ID: file:///storage/emulated/0/Pictures/train2014/COCO_train2014_000000542458.jpg, Date Taken: 1566866253000
2020-01-20 15:37:03.217 27527-27703/com.camerarolllazyload I/CameraRoll: Image ID: file:///storage/emulated/0/Pictures/train2014/COCO_train2014_00 …
```
> Fix for pagination on Android.

- example/js/CameraRollExample.js
The timestamp is a unix timestamp to set a date from a unix timestamp it needs to be set in milliseconds.
> Show correct date in example code

- .github/pull_request_template.md
Add local pr template, so that CHANGELOG.md can be removed from the checklist.
> chore(github): add new local PR template

- package.json
> chore: increase the max RN version to 62

- README.md
- android/src/main/java/com/reactnativecommunity/cameraroll/CameraRollModule.java
- ios/RNCCameraRollManager.m
- js/CameraRoll.js
- typings/CameraRoll.d.ts
This PR add support to get album list
Local test on real devices and simulators
> Get album list

- js/CameraRoll.js
- package.json
- yarn.lock
The master branch seems to be failing due to eslint error.
I've applied the lint error fix, and updated the community eslint-config while at it.
yarn validate:eslint
> update and fix lint error

- android/src/main/java/com/reactnativecommunity/cameraroll/CameraRollModule.java
Fix warning `[deprecation] GuardedAsyncTask(ReactContext) in GuardedAsyncTask has been deprecated`
Possibly related to https://github.com/react-native-community/react-native-cameraroll/issues/93
> Update deprecated functions

- ios/RNCCameraRollManager.m
This is a fix for the iOS-related issue when trying to save an image, as detailed here: #157 
This fix is courtesy of the code posted here: #159 
iOS 13 device
Attempt to save an image
| Android |    N/A     |
> Bugfix: Error Domain=PHPhotosErrorDomain Code=-1

- android/src/main/java/com/reactnativecommunity/cameraroll/CameraRollModule.java
Fixed 'Invalid column COUNT(*) as count' on CameraRoll.getAlbums() due to GROUP BY support removed in Android Q.
CameraRoll.getAlbums() has 2 issues:
1. Exception thrown: java.lang.IllegalArgumentException: Invalid column COUNT(*) as count with API Level 29.
2. Exception get swallowed and doesn't return the promise here https://github.com/react-native-community/react-native-cameraroll/blob/master/android/src/main/java/com/reactnativecommunity/cameraroll/CameraRollModule.java#L430 so the function called CameraRoll.getAlbums() never get into the `then` or the `catch` part from client perspective
For the issue #1, it looks like GROUP BY support is removed from Android Q, that's why is not working.
Related to: https://github.com/react-native-community/react-native-cameraroll/issues/174 …
> Fixed 'Invalid column COUNT(*) as count' on CameraRoll.getAlbums()

- .circleci/config.yml
Upgrades the build orb to resolve the node version build issue in #177
> chore: upgrade build orb

- README.md
Adds the missing bit where you have to explicitly ask permission.
#194 
> Adds docs for Android permissions

- android/src/main/java/com/reactnativecommunity/cameraroll/CameraRollModule.java
> fix put image npe.

- android/src/main/java/com/reactnativecommunity/cameraroll/CameraRollModule.java
As release 4.0.1 didn't fix #239. I made this fix.
Tested on Samsung A3 faulty videos
Some Android devices with faulty videos with zero length.
See #239
> fix: bug #239

- package.json
- react-native-cameraroll.podspec
See https://github.com/facebook/react-native/issues/29633#issuecomment-694187116
> fix: updated react dependency in podspec to enable build in Xcode 12 (for iOS >= 12)

- README.md
to make this project work on android 10 we will need to add android:requestLegacyExternalStorage="true" on application tag.
added that to readme so that people don't waste hours searching for it.
> updated readme for scoped storage changes

- README.md
Fixed links for CircleCI Badge image and url on README
CircleCI Badge displays correctly on README, and it links to the circle ci page for this repository
> docs: fix circle ci badge url

- package.json
- Issue React 18 https://github.com/react-native-cameraroll/react-native-cameraroll/issues/393
- [X ] I have tested this on a device and a simulator
> Update package.json to use React 18 as peer dependency

- README.md
> Docs outdated in android section

- README.md
- package.json
BREAKING CHANGE: new package namespace!
> chore(npm): migrate package @react-native-camera-roll/camera-roll namespace

- src/__tests__/CameraRollIOSPermissionTest.ts
Added some Unit Test cases for one of the files
We should be able to test the test cases in CircleCI
NA
NA
> Added UTs for CameraRollIOSPermission file

- android/src/main/java/com/reactnativecommunity/cameraroll/CameraRollModule.java
This fixes an issue (#421) a regression that occurred in 5.0.1.
> fix(android): retriever.release fix

- android/src/main/java/com/reactnativecommunity/cameraroll/CameraRollModule.java
> Issue 423: Fix save video on Android

- ios/RNCCameraRollManager.m
This is a follow up fix for #272 since the original author seems to be no longer active.
> Sergeymild/master: Save gif

- src/CameraRoll.ts
> fix call getParamsWithDefaults static method

- README.md
Updated docs for Android 13 permissions
> Updated docs for Android 13 permissions

- README.md
Updated docs for Android 13 ask permissions
- [ x ] I added the documentation in `README.md`
> Update docs for Android 13 ask permission

- android/src/main/java/com/reactnativecommunity/cameraroll/CameraRollModule.java
I was facing an issue regarding the library returning null tagged GPS location of video in android devices 
at (e.g at edges[0].node.image.location) .After some investigation I came to know that code for getting metadata of video for getting location coordinates is not integrated. So have integrated the same in this PR.
Try to get the video having location data by using 
CameraRoll.getPhotos({ assetType: 'Videos'})
Reqiuired an video in gallery with geo tagged location. For example : Clicking an video by setting location tags to switch on in camera settings.
Try to fetch  any .MP4 or video file by with location data by CameraRoll.getPhotos and see you will be getting location data of video like 
location: { longitude: 122.0839, latitude: 37.422 }
| ------- | …
> Fixed always getting null location of video file.

- src/useCameraRoll.ts
fixes #485
| iOS     |    ✅   |
> fix: make useCameraRoll functions to be shallow equal

- README.md
This just fixes a typo in the README file, no code changes.
> Fix "Andoid" typo in README

- README.md
Fixes #494
Also removes the outdated instructions for Android 13, we already support scoped storage in the SDK so we don't need to add the legacy attribute anymore
NA
| iOS     |    NA    |
| Android |  ✅   |
> docs: update with android 13 and supported permissions

- android/build.gradle
Reference: https://github.com/react-native-community/discussions-and-proposals/issues/671
> feat(android): Add support for upcoming React Native 0.73

- README.md
- ios/RNCCameraRoll.mm
- src/CameraRoll.ts
- src/NativeCameraRollModule.ts
Added getPhotoThumbnail method for iOS only.  These changes are based off of the ideas from @dokkis in #168.
I would like to add for Android at some point.  (I think @dokkis came close to a working solution for Android?)
Comments/Questions
1. Thumbnails are generated for both images & videos.  I've added sample code to the README.
2. I ultimately used `getPhotoByInternalID` as a starting point / guide.
3. I use `UIImageJPEGRepresentation` (returns the image as JPEG) for the base64 encoding - regardless of photo/video or extension.
4. I tried implementing caching with `PHCachingImageManager` but ran into serious performance issues once testing on my device.  When testing on the simulator I did not see performance issues - and I also did not really notice any performance increases - so I'm …
> added getPhotoThumbnail

- README.md
- example/js/CameraRollExample.js
- example/js/CameraRollView.js
- ios/RNCCameraRoll.mm
- src/CameraRoll.ts
- src/NativeCameraRollModule.ts
This PR resolves the conflicts from [324](https://github.com/react-native-cameraroll/react-native-cameraroll/pull/324).  I applied @valentynberehovyi's changes from that PR to the latest code.
> Added basic SmartAlbum support for iOS (conflicts resolved)

- FabricExample/ios/Podfile.lock
- README.md
- ios/RNCCameraRoll.h
- ios/RNCCameraRoll.mm
- src/CameraRoll.ts
- src/NativeCameraRollModule.ts
Add a new event called `onProgressUpdate` that notifies the app about the progress of the image/video being downloaded from iCloud.
Sometimes when calling `iosGetImageDataById`, the image/video can be downloaded from iCloud. To be able to receive the progress of this download, you need to add a listener to the `onProgressUpdate` event and use it to render on the UI.
The event generated will be an object containing the image id (`id`) and the progress of the download (`progress`). The `id` is a string with the `internalID` you used to call `iosGetImageDataById`. The `progress` is a double ranging from 0 to 1, where 0 represents the start of the download and 1 represents the completion of the download.
```javascript
import { progressUpdateEventEmitter } from …
```
> Add a new event called onProgressUpdate

- ios/RNCCameraRoll.mm
Fixes #598 by properly copying over EXIF and GPS metadata tags when saving images. 
Instead of loading the file as NSData and converting it to a UIImage, we directly pass the image path to the `PHAssetChangeRequest`, which also takes EXIF and GPS tags into account.
Just call save with EXIF tags. It works now.
> feat: Properly copy over EXIF and GPS metadata tags when saving

- android/src/main/java/com/reactnativecommunity/cameraroll/CameraRollModule.java
Added missing listeners for Android in Fabric, this fixes #600 
> Added noop add/remove listener functions for Android

- ios/PrivacyInfo.xcprivacy
- ios/RNCCameraRoll.xcodeproj/project.pbxproj
- react-native-cameraroll.podspec
Add Privacy Manifest for [File timestamp APIs](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api#4278393), .creationDate
> Add privacy manifest

- android/src/main/java/com/reactnativecommunity/cameraroll/CameraRollModule.java
New arch support was fixed in #601 but the type wasn't quite correct
COmpilation of my app now succeeds
RN0.74 with newarch enabled
It willcompile without errors
| iOS     |   N/A     |
> Fix add removeListeners argument type

- README.md
- android/src/main/java/com/reactnativecommunity/cameraroll/CameraRollModule.java
- ios/RNCCameraRoll.mm
- src/CameraRoll.ts
- src/NativeCameraRollModule.ts
This PR adds the album id on getAlbums response object. #592 
| iOS     |    ✅    |
> fetch album id

- android/src/main/java/com/reactnativecommunity/cameraroll/CameraRollModule.java
Reverts react-native-cameraroll/react-native-cameraroll#619
> fix(android): Revert "Fix add removeListeners argument type"

- FabricExample/App.tsx
- FabricExample/android/app/src/main/AndroidManifest.xml
- FabricExample/package.json
- FabricExample/yarn.lock
Updated the example to latest react-native version
> chore(example): Bumped react-native version to 0.74.2

- FabricExample/js/CameraRollExample.tsx
- ios/RNCCameraRoll.mm
> Preserve heic exif

- package.json
Adds RNCPHAssetUploader to modulesConformingToProtocol as RCTURLRequestHandler, to link RNCPHAssetUploader and fix error "No suitable URL request handler found for ph-upload://..." on new-arch
https://github.com/react-native-cameraroll/react-native-cameraroll/issues/669
Just try to send ph:// asset using fetch request
> feat: [IOS] Fix error "No suitable URL request handler found for ph-upload://..."
