- example/android/app/build.gradle
The issue with the Android tests on CircleCI is that it tests with the release version of the app but the Javascript was not bundled within it. This PR re-enables the Javascript bundling so the app can run correctly without a Metro packager running.
> test(android): Ensure the "release" app has the Javascript bundled

- ios/RNCCameraRollManager.m
Fixes [#27](https://github.com/react-native-community/react-native-cameraroll/issues/27) (iOS: Order when request assetType:All is incorrect)
> [FIX][iOS] All mediaTypes return order

- example/ios/CameraRollExample.xcodeproj/project.pbxproj
When the repo was first set up it assumed that the JS was bundled and persisted in the first CircleCI job. With the change to the CircleCI Orb, this was no longer the case and the bundling needs to happen when the iOS app is built.
To do this, I have reverted the "Bundle React Native code and images" build phase to just run the standard `node_modules/react-native/scripts/react-native-xcode.sh` script for all configurations.
> chore(CI): Fix iOS release build bundling so tests pass

- .circleci/config.yml
- .releaserc
Turns Android release/debug builds on commit back on (smoke test, e2e is still off)
Adds a publish step to CircleCI on master commits
> chore(ci) add publish step on master commits

- ios/RNCCameraRollManager.m
By collecting assets (aka photos) directly if `groupTypes` is `"All"` then we fix the ordering issue where some people were seeing old photos first, e.g. a slew of panoramas as the first photos listed.
Disclaimer: My Objective-C is extremely rusty. Very likely that I'm hacking around too much but this seems to work on my device in our project and it avoids a big if/else statement with mostly duplicated code.
> Fix #45 ordering of photos when groupTypes is All

- android/src/main/java/com/reactnativecommunity/cameraroll/CameraRollModule.java
This prevents the crash when the device contains images with a `#`.
This fixes https://github.com/facebook/react-native/issues/24468.
The guessing of the content type was introduced in https://github.com/react-native-community/react-native-cameraroll/commit/da20713a64858401bfaf0067b6659905f165a764#diff-7f48a66bcd0a56ced1913161061c6e3bR434
@kesha-antonov is there a specific reason why you opted to make use of guessing the mimetype from the uri instead of using the value reported by the media Cursor?
> Use the MimeType reported by the media Cursor instead of trying to guess the mime type from uri

- .gitignore
- android/src/main/java/com/reactnativecommunity/cameraroll/CameraRollModule.java
This PR tries to balance the intention of throwing the exception when groupType is supplied to an Android app running Cameraroll and the fact that now a default is supplied which causes #56 .
fixes #56
> Forced default groupType all fix

- README.md
- android/src/main/java/com/reactnativecommunity/cameraroll/CameraRollModule.java
- ios/RNCAssetsLibraryRequestHandler.m
- ios/RNCCameraRollManager.m
This PR restores the filename back to the image properties.  This works in both iOS and Android, as well as updated docs.  The propterty was still in the typescript definition.
This really is a subset/duplication of https://github.com/react-native-community/react-native-cameraroll/pull/30 except for being limited only to filename, but also including docs and android implementation.
> Add filename back into the image properties iOS and Android

- ios/RNCAssetsLibraryRequestHandler.m
Fixes #42, CFRelease(NULL) with video.
It seems like the fix was reverted at some point before v1.1.1
> fixes #42, again

- ios/RNCCameraroll.xcworkspace/contents.xcworkspacedata
When trying to open the workspace file with XCode I kept getting an error that XCode couldn't open the file. This fixes that error.
Open file in XCode.
A mac with XCode.
Double click the xcworkspace file. Apply changes and you'll be able to open the file.
> Remove unrecognised UTF8 tag from xcworkspace file

- ios/RNCAssetsLibraryRequestHandler.m
Uploading images from the Camera Roll used to be in JPEG format when assets were retrieved with `assets-library` protocol, but now they are returned as HEIC if stored that way. This breaks all apps relying on images being JPEGs.
These changes use the `isPHupload` flag already used to ensure that a video is correctly uploaded (not only the thumbnail), and applies conversion only when uploading.
I made and tested this patch on a view allowing to choose photos from the camera roll and then uploading them as `FormData`.
An iPhone or iPad configured to take pictures in HEIC format. (default on latest iOS versions)
1. Take a photo with the camera app
2. Get that photo's uri from the camera roll
3. Append it to a FormData
4. Check the `mime/type` => `image/heic`
| …
> Convert PHAsset to JPEG for uploading

- README.md
- android/src/main/java/com/reactnativecommunity/cameraroll/CameraRollModule.java
- ios/RNCCameraRollManager.m
- js/CameraRoll.js
- typings/CameraRoll.d.ts
This pull request fixes #59 by moving to the new PHAsset API on iOS and adding an implementation for Android.
I created a local app where I called `deletePhotos` with a single URI and with multiple URIs. Behaviour was as expected, e.g. that on iOS a confirmation dialog was presented, and on Android the files were deleted immediately.
I'd be happy to modify the example app in this repo to demonstrate this functionality, just need some guidance on what you'd like to see there.
- Photos must be on the device you wish to test on.
- Example app must be installed.
- Call `getPhotos` to get some URIs
- Call `deletePhotos` to delete some of them.
> Moved deletePhotos to use new PHAsset API and added an implementation for Android

- ios/RNCCameraRollManager.m
Fixes #86
This library is using a class that got deprecated in React Native `0.61.0`. (https://github.com/facebook/react-native/blob/0.61-stable/React/CoreModules/RCTImageLoader.h)
This PR makes it so we're now using the recommended implementation.
Save an image to the camera roll and make sure no yellow box appears and that the image is successfully saved.
In the current version of the library, save a photo to the camera roll and observe the yellow box.
| Android |    N/A     |
> Fix warning for deprecated RCTBridge interface for RCTImageLoader

- android/src/main/java/com/reactnativecommunity/cameraroll/CameraRollModule.java
Fix outlined in #97 
Screenshots taken in Android 10 are no longer tagged with DATE_TAKEN but only DATE_ADDED. This causes screenshots taken in Android 10 to appear at the bottom of a potentially very long list.
I have no solid test plan. I've tested it locally.
A photo library with at least 10 items, to clearly see how screenshots are shown last.
See issue
> Fix #97 Android 10 screenshot sorted incorrectly

- ios/RNCCameraRollManager.m
After upgrading to 1.3.0 that includes #87, my builds started to fail on the step to link react-native-cameraroll with the following message:
`Undefined symbol: _OBJC_Class_$_RCTImageLoader`.
I'm not sure what @tomtargosz's environment is like that allowed this to work, but it does not seem to work in 0.61.x with autolinked (cocoapods) dependencies. It looks like the recommendation made in that file by the react-native team is incorrect. I'm also not 100% confident this will work with RN < 0.60. I suspect the way `react-native-svg` fixed this may be backwards compatible - see [this commit](https://github.com/react-native-community/react-native-svg/commit/5452144468c2fbc157db7383e00ebd72bdad6af0) and [this one that specifically notes …
> Fix build error in RNCCameraRollManager.m

- android/src/main/java/com/reactnativecommunity/cameraroll/CameraRollModule.java
Use DCIM dir for saveToCameraRoll. We noticed an increase in `External media storage directory not available` errors for our app. We noticed that the react-native-cameraroll in the current react-native project is using the DCIM directory, and was changed from the MOVIES and PICTURES dir quite a while ago. 
See here: https://github.com/facebook/react-native/blame/15ecb60d6deb96fcb7b0ef70faccd10594ededa3/ReactAndroid/src/main/java/com/facebook/react/modules/camera/CameraRollManager.java#L136
- N/A I added the documentation in `README.md`
- N/A I updated the typed files (TS and Flow)
- N/A I added a sample use of the API in the example project (`example/App.js`)
> [Android] Use DCIM direcotry for saveToCameraRoll

- README.md
- android/src/main/java/com/reactnativecommunity/cameraroll/CameraRollModule.java
- ios/RNCCameraRollManager.h
- ios/RNCCameraRollManager.m
- typings/CameraRoll.d.ts
This PR is a replacement of #120 that I closed accidentally. So I am going to copy the description below.
Add `fromTime` and `toTime` to `getPhotos` to get media items in between
Manual test on my device
> Support filter media items between dates

- android/src/main/java/com/reactnativecommunity/cameraroll/CameraRollModule.java
- typings/CameraRoll.d.ts
Delete photos returns a promise in the underlying implementation, currently a boolean on iOS and null on Android.
This PR makes them both return a boolean, and updates the Typescript types to match.
Best tested in an application.
> Delete Photos - Make Returns Consistent

- ios/RNCCameraRollManager.m
Pr of changes listed in https://github.com/react-native-community/react-native-cameraroll/issues/125
Allows for ios to save metadata and images
- [x ] I have tested this on a device and a simulator
> changes to fix IOS MetaData

- ios/RNCCameraRollManager.m
Removes an unused import that caused the build to fail on RN >= 0.60
Fixes https://github.com/react-native-community/react-native-cameraroll/issues/147
N/A
> remove unused import that breaks the build for RN >= 0.60

- android/src/main/java/com/reactnativecommunity/cameraroll/CameraRollModule.java
REVERT: fix: Update deprecated functions (#149)
reverted to fix build issues on older React Native versions (deprecation warnings are a smaller problem)
> fix: rollback getExceptionHandler change

- ios/RNCCameraRollManager.m
This is a fix for cases when a user has albums with `'` in their names.
1. Create an album on iOS device with `'` in its' name, for example `Men's Health`.
2. Try to use a `getPhotos` method.
> Fix getPhotos crash if there is a quote in an album name

- android/src/main/java/com/reactnativecommunity/cameraroll/CameraRollModule.java
LATITUDE and LONGITUDE are deprecated in API level 29, image coordinates are null. we manually obtained location metadata using ExifInterface
> Manually obtain location metadata using ExifInterface

- ios/RNCCameraRollManager.m
- ios/RNCCameraroll.podspec
- ios/RNCCameraroll.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
Changed the url to the git repository of the project in Podspec. Installing the pod dependency was not warking with the wrong url.
> Fixed reference to git repository in Podspec file

- android/src/main/java/com/reactnativecommunity/cameraroll/CameraRollModule.java
The error is still reproducing for image location on API 29
I added checking for android API. Set LONGITUDE and LATITUDE for images if API < 29
This is an error screenshot:
> Fixed 'Invalid column longitude' in Android 29 SDK 

- README.md
- android/src/main/java/com/reactnativecommunity/cameraroll/CameraRollModule.java
- ios/RNCCameraRollManager.m
- js/CameraRoll.js
- typings/CameraRoll.d.ts
Summary
Added fileSize for getPhotos API and changed type returned by iOS implementation to be mimetype to align with the Android implementation.
device and emulators for iOS and Android
Run the example package and verified that there is no regression.
Verified that fileSize is included in both iOS and Android looking at output as we console.log the entire data object.
Verified that `type` in iOS now returns the mimetype, same as it is in Android.
Addressed an existed TODO and reach consistency across platforms.
> Added fileSize for getPhotos API

- README.md
- js/CameraRoll.js
> fix: deprecate saveToCameraRoll

- README.md
- android/src/main/java/com/reactnativecommunity/cameraroll/CameraRollModule.java
Adjusted README and implemented `save` function to Android to use `DCIM` if no album is provided.
Problem 1:
First of all there is a bug in the current handling of type param for Android in the save function. From doc it's either video or photo, but on implementation https://github.com/react-native-community/react-native-cameraroll/blob/master/android/src/main/java/com/reactnativecommunity/cameraroll/CameraRollModule.java#L133 it's checking over mov value. If I try to pass mov as value from JS, I got an error on the enum check. So there is no way to reach the current Environment.DIRECTORY_MOVIES dir in Android.
Problem 2:
If I try to simply replace Environment.DIRECTORY_PICTURES with Environment.DIRECTORY_DCIM, the save photo works (no errors) but I never see the new album appearing in …
> Use DCIM folder when album is not provided on Android.

- README.md
- android/src/main/java/com/reactnativecommunity/cameraroll/CameraRollModule.java
- example/js/GetPhotosPerformanceExample.tsx
- ios/RNCCameraRollManager.m
- js/CameraRoll.js
- typings/CameraRoll.d.ts
**This is another change that is not backwards compatible**
I realized that the Android implementation still had poor performance since it looped through individual images to populate `image.width/height` (some of the time) and `image.playableDuration` (for every video).
Excluding `playableDuration` in particular improves performance significantly when the user has videos.
This change:
- Adds `include` params for `image.width`, `image.height`, and `image.playableDuration`
- Refactors Android code to respect those and avoid looping if the params are excluded
- Makes iOS code respect it too
- Adds documentation
Side change:
- This also deletes the useless `isStored` output that's just a boolean always set to true on iOS
Added toggles to GetPhotosPerformanceExample.
| iOS | Android |
| --- | …
> Added imageSize and playableDuration to `include` param, deletes isStored

- react-native-cameraroll.podspec
After adding react-native-community/react-native-cameraroll to a project, running pod install fails with an error indicating that tag 2.0.0 cannot be found.
On investigation I found that version tags all have a 'v' prefix. Adding the v prefix in the appropriate place in the podspec fixed the error. This makes react-native-cameraroll consistent with other components in the react-native-community family.
* react-native init myproject
* yarn add @react-native-community/react-native-cameraroll
* cd ios
* pod install
> Fix for error during pod install. Tags have v prefix.

- ios/RNCAssetsLibraryRequestHandler.m
This reverts commit c958493441edf622dbc320b9e1319298b8123481.
fixes #193
BREAKING CHANGE: this reverts forcing all mime types to jpeg on upload, which loses GIF data
> fix: Revert "Convert PHAsset to JPEG for uploading"

- .circleci/config.yml
Cleanup of the CircleCI workflow, there's no need to make publish job dependant of analyze, since analyze is already dependent on checkout_code
New pipeline:
> Remove unnecessary publish job requirement

- ios/RNCCameraroll.podspec
Latest Xcode 12 fails to build while without a module to depend on `React-Core` directly hence this change is necessary for all native modules on iOS. This change requires React Native 0.60.2 or newer. For more details please check: https://github.com/facebook/react-native/issues/29633#issuecomment-694187116
Use this branch to install with an app running on Xcode 12.
> fix: Xcode 12 compatibility

- README.md
**Motivation**
Add the missed part of change to #183 which deprecate `saveToCameraRoll()` and use the recommended `save()` in README Usage
> doc: readme usage use recommended `save()`

- android/src/main/java/com/reactnativecommunity/cameraroll/CameraRollModule.java
On android, we discovered an issue where the "timestamp" would be just `"0"` on several test devices. 
To solve this we added this:
- When dateTaken is 0 retrieve value from dateAdded
- Added additional modified field.
We tested this on several physical test devices as well as on emulators.
Can't exactly tell how to reproduce the issue, that the dateTaken was 0 on some devices.
> fix: (Android) Fixed issue where timestamp was "0"

- ios/RNCCameraRollManager.m
In `getPhotos` API call, fetching `filename` and `fileSize` may encounter null pointer on iOS platform, resulting an exception thrown while constructing the result dictionary object.
A typical crash report looks like below:
```
terminateReason: NSInvalidArgumentException *** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[4]  
osVersion: iOS 11.2.6 (15D100)
CurrentBackTrace:
CoreFoundation           0x000000018253b164 ___exceptionPreprocess + 123
libobjc.A.dylib          0x0000000181784528 _objc_exception_throw + 55
CoreFoundation           0x00000001824d3c9c __CFThrowFormattedException + 111
CoreFoundation           0x000000018240bfd0 -[__NSPlaceholderDictionary initWithObjects:forKeys:count:] + 351
CoreFoundation …
```
> fix(iOS): prevent crash for fileSize fetching

- README.md
Without this attribute in place the app is not able to render image having the `uri` of the file.
[Ofiicial documentation link](https://developer.android.com/training/data-storage/use-cases#opt-out-scoped-storage)
I spent 2 hours investigating why my images are not rendered, until I found [this comment](https://github.com/react-native-cameraroll/react-native-cameraroll/issues/219#issuecomment-671411010), so I thought it might be better to have it described in the README.
> Document usage of requestLegacyExternalStorage for Android 10 (API level 29) or higher

- example/js/CameraRollExample.js
- js/CameraRoll.js
- package.json
Build in my app fails because `fbjs` require cannot be resolved. Instead, it should be added to this pacakge's dependencies. But since we only use invariant, I added invariant instead of fbjs.
> fix: Remove fbjs in favor of `invariant` lib

- ios/RNCCameraRollManager.m
When fetching with afterCursor != nil and include filename or fileSize or mime, performance will reduce heavily because we have to loop through all previous assets and call [PHAssetResource assetResourcesForAsset], which is slow and redundant
| iOS     |    ✅    |
> Improve performance when fetching with afterCursor != nil

- ios/RNCCameraRollManager.m
This patch fixes an issue (#292) when trying to save to camera roll on iOS 14 or later. The `requestPhotoLibraryAccess` function requests read and write access on the Photo library. Which triggers a system popup to request access as seen in #292.
The fix adds an extra parameter to determine if `PHAccessLevelReadWrite` or `PHAccessLevelAddOnly` should be used when requesting access to the Photo library.
This was tested using the example app and our internal app which uses only uses the `saveToCameraroll` feature.
A device or simulator with iOS 14+ and a device or simulator with < iOS 14.
Same as above.
> iOS: Use PHAccessLevelAddOnly for saveToCameraRoll

- android/src/main/java/com/reactnativecommunity/cameraroll/CameraRollModule.java
I have fixed issue #435 
I changed the android mediaStore query to filter photos based on timeStamp.
1- Need a device that contains photos that the taken date for them is null (if you add a photo to your devise manually the taken date will be null )
1- get all photos by getPhotos method
2- try to filter that picture based on timeStamp
3- you cannot filter the pictures that their taken dates is null
> bugfix: filter by timestamp issue is fixed.

- README.md
Removes a sentence in the readme that I think was accidentally copied over when extracting from react-native-hooks package
Read the diff ☺️ 
n/a
n/a
- [n/a] I have tested this on a device and a simulator
- [n/a] I added the documentation in `README.md`
- [n/a] I updated the typed files (TS and Flow)
- [n/a] I added a sample use of the API in the example project (`example/App.js`)
> doc: remove accidental mention of clipboard

- README.md
- src/CameraRoll.ts
I was facing an issue regarding the library not detecting automatically the file type when calling the `save()` method. After some investigation I realized that the problem is that some files have uppercase extensions like **.MOV** and **.MP4** which weren't caught by the auto type detection. 
Try to download any .MP4 or .MOV file using `type: 'auto'`
A .MOV or .MP4 url. 
Try to download any .MP4 or .MOV file using `type: 'auto'` and see if it works now
- [n/a] I updated the typed files (TS and Flow)
- [n/a] I added a sample use of the API in the example project (`example/App.js`)
> fix: add lowercase to auto detection type

- README.md
- android/src/main/java/com/reactnativecommunity/cameraroll/CameraRollModule.java
- android/src/main/java/com/reactnativecommunity/cameraroll/Utils.java
- ios/RNCCameraRollManager.m
- src/CameraRoll.ts
Hello everyone.
**CameraRoll.getPhotos({})** function does not return a file extension for iOS. This was restrictive behavior. 
To solve this, an optional parameter **"fileExtension"** was added to the **"include"** array. 
Made in two platforms to maintain code standardization.
**In short, you can now;**
```
CameraRoll.getPhotos({
include: ['fileExtension'],
})
```
**Here are some previous threads on this issue:**
https://github.com/react-native-cameraroll/react-native-cameraroll/issues/218
https://github.com/react-native-cameraroll/react-native-cameraroll/issues/301
https://github.com/react-native-cameraroll/react-native-cameraroll/issues/52
https://github.com/react-native-cameraroll/react-native-cameraroll/issues/12
| iOS     |    ✅ …
> Android and Ios file extension support (for CameraRoll.getPhotos )

- README.md
- android/src/main/java/com/reactnativecommunity/cameraroll/CameraRollModule.java
- src/CameraRoll.ts
The **motivation** for me working on this is that I was affected by this issue. This addresses #212  
The **reason** I'm creating this pull request is that I am **required** to make a contribution to an open source project as part of a class at my university, so **please take this as a suggestion at a possible solution and not a full implementation of the solution.**
This is mostly the same as #278 except it returns the correct order of width-height instead of the user having to do it later as suggested by @HyopeR 
Before:
After:
Get in the possession of an image with rotation in it's exif orientation data.
> Suggest a fix for for width and height being flipped in imageSize property on Android by using orientation

- android/src/main/java/com/reactnativecommunity/cameraroll/CameraRollModule.java
I have recently contributed #454, reading through the Android API documentation some more I have found that it is possible that an exception can be thrown when reading null orientation. 
[Cursor documentation](https://developer.android.com/reference/android/database/Cursor#getInt(int))
I have not been able to get an exception to be thrown on my test device (using an image with no EXIF data), but it's possible it would be thrown on other devices.
So I am suggesting adding a check for `isNull` before trying to read the orientation.
```java
if(!media.isNull(orientationIndex)) {
int orientation = media.getInt(orientationIndex);
if (orientation >= 0 && orientation % 180 != 0) {
int temp = width;
width = height;
height = temp;
}
}
```
and
```java
if(media.isNull(orientationIndex)) { …
```
> Handle Null case when reading orientation on Android

- android/src/main/java/com/reactnativecommunity/cameraroll/CameraRollModule.java
`Uri.getPath` returns a path without the schema.
`MimeTypeMap.getFileExtensionFromUrl` returns null if a schema is not provided.
Fixed by replacing `getPath` with `getString`, `getString` returns an encoded path with schema.
Android only.
Save a video file to the camera roll.
Expected behaviour: no error, video is saved
See thread: https://github.com/react-native-cameraroll/react-native-cameraroll/issues/423
> fix: save video error (Android)

- android/build.gradle
Change in android build.gradle file. Renamed clipboard to cameraroll instead.
n/a
n/a
n/a
- [n/a] I have tested this on a device and a simulator
- [n/a ] I added the documentation in `README.md`
- [n/a ] I updated the typed files (TS and Flow)
- [n/a ] I added a sample use of the API in the example project (`example/App.js`)
> chore: remove accidental mention of clipboard

- android/src/main/java/com/reactnativecommunity/cameraroll/CameraRollModule.java
* What issues does the pull request solve? Please tag them so that they will get automatically closed once the PR is merged
Resolve the issue: https://github.com/react-native-cameraroll/react-native-cameraroll/issues/468
* How did you implement the solution?
The return value of `ContentResolver#insert()` is `nullable`, added a null-check and early termination before utilizing it as an input.
```java
ContentResolver{
// ...
public final @Nullable Uri insert(@RequiresPermission.Write @NonNull Uri url,
@Nullable ContentValues values) {
return insert(url, values, null);
}
}
```
* What areas of the library does it impact?
`CameraRollModule` in `Android` project.
Save a video file to the camera roll.
Expected behaviour: no error, video is saved
| ------- | :---------: …
> fix: npe when inserting of ContentResolver

- FabricExample/js/CameraRollExample.js
- README.md
- android/src/main/java/com/reactnativecommunity/cameraroll/CameraRollModule.java
- example/js/CameraRollExample.js
- ios/RNCCameraRoll.mm
- src/CameraRoll.ts
- src/NativeCameraRollModule.ts
I need to get the modification date from an asset. I checked the code and saw that there already was a `modified` field on Android even if it was not documented and that there was nothing on iOS. So what I did : 
- rename `modified`to `modificationTimestamp` on Android
- return `modificationTimestamp` on iOS
- update documentation and type
**iOS**
- Open Photos app
- Choose a photo
- Click Edit
- Do a random edit and click Done
- Check that the lib return correct `timestamp` and `modificationTimestamp`
**Android**
I did not find an app which modify a photo. Google Photos creates a copy. So `timestamp` and `modificationTimestamp` are the same which is correct.
> Add modificationTimestamp field

- FabricExample/js/CameraRollExample.js
- README.md
- android/src/main/java/com/reactnativecommunity/cameraroll/CameraRollModule.java
- example/js/CameraRollExample.js
- ios/RNCCameraRoll.mm
- src/CameraRoll.ts
- src/NativeCameraRollModule.ts
I need to know if a photo is a live photo. So I added a `subTypes` array inside node to get `PHAssetMediaSubtype` data. Possible values in subTypes : 
- 'PhotoPanorama'
- 'PhotoHDR'
- 'PhotoScreenshot'
- 'PhotoLive'
- 'PhotoDepthEffect'
- 'VideoStreamed'
- 'VideoHighFrameRate'
- 'VideoTimelapse'
`subTypes` array is always [] on Android.
**iOS**
- Take a photo with HDR or a live photo and check that the lib return the correct values in `subTypes`.
**Android**
Check that `subTypes`is always [].
| Android |    ✅   (but return nothing)  |
> feat: Add subTypes field to know if a photo is a live photo

- README.md
- ios/RNCCameraRoll.mm
Hi!
I don't really know ObjC, but I played a bit with this package to understand why iosGetImageDataById did not retrieve data for videos.
* Probably solves the upload dilemma:
#135 #195 #52 #449 
There's a small example in README on how to **upload assets** without any workarounds, hacks or deprecated packages. (Works for images/gifs/videos)
* What is the feature? 
Missing video handling
* How did you implement the solution?
Reading some docs & trial and error method
* What areas of the library does it impact?
[ios/RNCCameraRoll.mm](https://github.com/react-native-cameraroll/react-native-cameraroll/compare/master...vforvasile:react-native-cameraroll:fix/video-iosGetImageDataById?expand=1#diff-28e289c88abb9ed3d3e6ea1eaa4412e669751e82738fbfbea437c3ba9c21e9d1)
Would be great if anyone could …
> Fix iosGetImageDataById for videos

- android/build.gradle
Fixes the build error 
```Type com.reactnativecommunity.webview.BuildConfig is defined multiple times: [SRC]/node_modules/@react-native-camera-roll/camera-roll/android/build/.transforms/2d1e59288a3d562c2f5d50d42cefe703/transformed/classes/classes.dex, [SRC]/node_modules/react-native-webview/android/build/.transforms/7fdaa75708060e982f026ee0f7088828/transformed/classes/classes.dex``` on adroid
n/a
n/a
yarn android
| iOS     |    ✅    |
> Fixes android build error webview namesapce

- README.md
- ios/RNCCameraRoll.mm
- src/CameraRoll.ts
- src/NativeCameraRollModule.ts
Return subtype in get albums to be able to check for example if an album is an iCloud Shared Albums. Combined with https://github.com/react-native-cameraroll/react-native-cameraroll/pull/525, it allows to do thing without anything related to iCloud Shared Albums, or with iCloud Shared Albums.
Before these two PRs, getAlbums returned iCloud Shared Albums, and getPhotos did not return photos in iCloud Shared Albums.
| Android |    ❌ (not relevant)  |
> Include subtype in get albums. iOS only.

- README.md
- ios/RNCCameraRoll.mm
- src/CameraRoll.ts
If you get an image by it's ID, the quality is always 100%, which results in large files.
Allow setting a custom quality.
BREAKING CHANGE: convertHeic replaced by options object
Before:
```
const convertHeic = true;
CameraRoll.iosGetImageDataById(internalID, convertHeic);
```
After:
```
CameraRoll.iosGetImageDataById(internalID, {
convertHeic: true,
quality: 0.8
});
```
> feat(ios)!: allow setting a custom conversion quality

- android/build.gradle
After Merge `Add support for upcoming React Native 0.73` #505 https://github.com/react-native-cameraroll/react-native-cameraroll/commit/2e4851e, cause `undefined.camerarollpackage` #508 #522
This code will remove package from AndroidManifest.xml next time, If RN version < 0.71 cause `undefined.camerarollpackage`
```js
if(shouldUseNameSpace){
manifestContent = manifestContent.replaceAll(
PACKAGE_PROP,
''
)  
}
```
So I Add `REACT_NATIVE_VERSION >= 71`
> chore: build.gradle shouldUseNameSpace add RN version >= 71

- android/src/main/java/com/reactnativecommunity/cameraroll/CameraRollModule.java
- android/src/paper/java/com/reactnativecommunity/cameraroll/NativeCameraRollModuleSpec.java
This PR fixes issue #547.  I added the getPhotoThumbnail method signature to java files for Android.  This fixes the error, however this method is still not yet implemented for Android.
> added getPhotoThumbnail signature to java files for Android

- android/build.gradle
Fix the React Native version check for deciding whether to add the `namespace` property on the Android Gradle configurations.
The current logic, in addition to being duplicated, also resolves the **major** (not minor) version of RN, which currently evaluates to `0` (given the `0.73.0` tag, for example), always failing to apply the namespace.
Applying the already existing `REACT_NATIVE_MINOR_VERSION` variable fixes the issue and removes the duplicated code.
- Create a brand new RN 0.73 project
- `npx react-native@latest init AwesomeProject`
- Install this library
- `yarn add @react-native-camera-roll/camera-roll`
- Run the app and confirm that it successfully builds the app
- `yarn android`
Either logging the values manually or attaching the library to a RN project.
See `Test Plan` above. …
> Fix RN version check for adding Gradle namespace

- FabricExample/ios/Podfile.lock
- README.md
- android/src/main/java/com/reactnativecommunity/cameraroll/CameraRollModule.java
- example/ios/Podfile
- ios/RNCCameraRoll.mm
- jest.setup.js
- src/CameraRoll.ts
- src/NativeCameraRollModule.ts
- src/__mocks__/nativeInterface.ts
- src/__tests__/CameraRollTest.ts
- src/__tests__/useCameraRoll.ts
**TL;DR: Adds `saveAsset(): Promise<PhotoIdentifier>` to get the full photo asset immediately after saving.**
---
This PR changes the behaviour of the native `saveToCameraRoll` function to return the full `PhotoIdentifier` instead of just the URI.
The motivation behind this is feature request #568.
This is useful if you want to append the image to state and render it immediately, e.g. in Gallery or Camera apps (such as [ShadowLens](https://mrousavy.com/projects/shadowlens)), because you can use the `id` for equality comparisons and keys, and elements like width and height are immediately available.
To not make this breaking, `save()` will still return a string (the URI), and a new method called `saveAsset()` has been introduced, which returns the full photo asset.
Save a photo by calling …
> feat: Return full `PhotoIdentifier` in save()

- react-native-cameraroll.podspec
Quick fix for using `install_modules_dependencies(s)` if it is available since it works on both archs and is recommended by the core team. It is also necessary for new arch to work on RN >= 0.73
> Update react-native-cameraroll.podspec for newest RN on Fabric

- FabricExample/ios/Podfile.lock
- FabricExample/js/GetPhotosPerformanceExample.tsx
- README.md
- android/src/main/java/com/reactnativecommunity/cameraroll/CameraRollModule.java
- ios/RNCCameraRoll.mm
- src/CameraRoll.ts
- src/NativeCameraRollModule.ts
This PR is divided in 2 parts.
1. Return sourceType
Allow to return the source type of an asset. On iOS, the source type of an asset can be the user library (`sourceType` will be `UserLibrary`) or an iCloud Shared Album (`sourceType` will be `CloudShared`). Linked to this PR https://github.com/react-native-cameraroll/react-native-cameraroll/pull/525 which allows to return assets from iCloud Shared Albums.
It is not very interesting on Android so it will always return `UserLibrary`. 
2. and fix missing filename and fileSize
In the meantime, I fixed missing filename and fileSize as reported in this issue https://github.com/react-native-cameraroll/react-native-cameraroll/issues/576. More information in commits messages.
- Have assets in the user library and in an iCloud Shared Albums
- Check …
> Return sourceType and fix missing filename and fileSize

- FabricExample/ios/Podfile.lock
- ios/RNCAssetsLibraryRequestHandler.h
- ios/RNCAssetsLibraryRequestHandler.m
- ios/RNCPHAssetLoader.h
- ios/RNCPHAssetLoader.m
- ios/RNCPHAssetUploader.h
- ios/RNCPHAssetUploader.m
- package.json
Adds a new file called `RNCPHAssetLoader` - this implements `RCTImageURLLoader` and can be injected into the app's URL loaders using the new `codegenConfig` option.
On new arch, `ph://` and `asset-library://` assets now load perfectly fine.
Before this, they would fail to load.
- Fixes https://github.com/react-native-cameraroll/react-native-cameraroll/issues/631
Just load a `ph://` asset using `<Image>` component.
In FabricExample, just render the Images:
> feat: Create `RNCPHAssetLoader` to load `ph://` and `asset-library://` assets on new-arch

- android/src/main/java/com/reactnativecommunity/cameraroll/Utils.java
Now if we try to do a saveAssest with a filename that contains characters other than `[a-zA-Z_0-9\.\-\(\)\%]`, we get an error. This is because MimeTypeMap.getFileExtensionFromUrl cannot recognise the extension. 
MimeTypeMap.getFileExtensionFromUrl support inly URL like strings. While file names may contain spaces, apostrophes, and other characters. According to the https://issuetracker.google.com/issues/36911541?pli=1 and 
https://stackoverflow.com/questions/8589645/how-to-determine-mime-type-of-file-in-android I propose this solution
Try to save the file with a name that contains spaces.
> fix(android): Add supporting whitespaces and other symbols in the file name

- ios/RNCCameraRoll.mm
Handle cases in the `getPhotoThumbnail` method when `requestImageForAsset` returns `nil` for some reason. For example, for corrupted files because of some iCloud internal failure.
Resolves https://github.com/react-native-cameraroll/react-native-cameraroll/issues/638
1. Find a corrupted file (image/video).
2. Try to call `getPhotoThumbnail` with its internal id. 
It's hard to reproduce because there are no steps to corrupt the asset file as it bugs itself—the most common scenario is some internal failures in iCloud with old videos.
-
> fix(iOS): getPhotoThumbnail crash when asset is corrupted

- android/build.gradle
When using react native with a non-official file strcuture, build fails.
> [react-native-cameraroll] Unable to resolve react-native location in node_modules. You should add project extension property (in app/build.gradle) REACT_NATIVE_NODE_MODULES_DIR with path to react-native.
Implement functions based on exception information.
If the REACT_NATIVE_NODE_MODULES_DIR property not configured, fallback to the previous implementation.
> chore(Android): Support custom react-native directory configration

- android/src/main/java/com/reactnativecommunity/cameraroll/CameraRollPackage.java
This change is being made because React Native 0.80.0 generates a runtime error, causing a null value.
> fix: return an empty list instead of null in getViewManagerNames
